name: gemini_nano_android
description: A Flutter plugin to access on-device Gemini Nano models via Android AI Core. Enables offline inference and privacy-first text generation.
version: 0.1.0
homepage: https://github.com/Piero16301/gemini_nano_android

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.pmorales.gemini_nano_android
        pluginClass: GeminiNanoAndroidPlugin

topics:
  - ai
  - gemini
  - android
  - llm
  - offline
